/**
 *  This is generated file. Do not edit !!
 *
 *  @formatter:off
 *
 */
/* tslint:disable */
export const WidgetsRulesRule = 'ɵ/**ɵ * @licenseɵ * Copyright 2017 SAP Aribaɵ *ɵ * Licensed under the Apache License, Version 2.0 (the "License");ɵ * you may not use this file except in compliance with the License.ɵ * You may obtain a copy of the License atɵ *ɵ * http://www.apache.org/licenses/LICENSE-2.0ɵ *ɵ * Unless required by applicable law or agreed to in writing, softwareɵ * distributed under the License is distributed on an "AS IS" BASIS,ɵ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.ɵ * See the License for the specific language governing permissions andɵ * limitations under the License.ɵ *ɵ * Based on original work: MetaUI: Craig Federighi (2008)ɵ *ɵ */ɵɵɵfield {ɵ    type  {ɵ       component:StringComponent;ɵ        bindings:{ɵ          value:$value;ɵ          id: ${properties.get("field")};ɵ          placeholder:${properties.get("label")};ɵ        };ɵ    }ɵɵ    type=(String, string) {ɵ        editable  {ɵ            component:PlatformInputModule;ɵ            bindings:{ɵ               id:${ properties.get("field")};ɵ               name:${ properties.get("field")};ɵ               ngModel: $value;ɵ               readonly:${ properties.get("readonly")};ɵ               type:"text";ɵ            };ɵ        }ɵɵ    }ɵɵ    component=(StringComponent,LinkComponent, PlatformInputModule) {ɵ        @trait=bold {ɵ            wrapperComponent:GenericContainerComponent;ɵ            wrapperBindings: { tagName:b; };ɵ        }ɵ        @trait=italic {ɵ            wrapperComponent:GenericContainerComponent;ɵ            wrapperBindings: { tagName:i; };ɵ        }ɵ        @trait=heading1 {ɵ            wrapperComponent:GenericContainerComponent;ɵ            wrapperBindings: { tagName:h1; };ɵ        }ɵ        @trait=heading2 {ɵ            wrapperComponent:GenericContainerComponent;ɵ            wrapperBindings: { tagName:h2; };ɵ        }ɵ        @trait=heading3 {ɵ            wrapperComponent:GenericContainerComponent;ɵ            wrapperBindings: { tagName:h3; };ɵ        }ɵ    }ɵ}ɵɵclass {ɵ    @trait=fourZones {ɵ        zones: [zOne, zTwo, zThree, zFour, zDetail];ɵ        fourZoneLayout:true;ɵ    }ɵɵ    @trait=oneZone {ɵ       zones: [zOne, zDetail];ɵ    }ɵɵ    operation=(create,edit,view,search) {ɵ        trait: fourZones;ɵ    }ɵɵ}ɵ@traitGroup=FormZones {ɵ    @trait=fourZones;ɵ    @trait=oneZone;ɵ}ɵɵɵlayout {ɵ    @trait=Form {ɵ      visible:true;ɵ      component:MetaFormGroup;ɵ      bindings:{ɵ        columnLayout:${properties.get("layoutPattern")};ɵ        mainTitle:${properties.get("mainTitle")};ɵ      };ɵ    }ɵɵ    component=MetaFormGroup {ɵ      @trait=noLabelLayout;ɵ    }ɵɵ    layout_trait=noLabelLayout class {ɵ      bindings:{ɵ        noLabelLayout:true;ɵ      };ɵ    }ɵɵ}ɵɵ~class layout=(Inspect, SearchForm) {component:StringComponent; bindings:{value:null; }; }ɵɵ';
/* tslint:disable */
/**
 *  @formatter:on
 *
 */
 