export interface UserCSV {
  UniqueName: string;
  PasswordAdapter: string;
  Name: string;
  EmailAddress: string;
  Supervisorpa: string;
  Supervisor: string;
  DefaultCurrency: string;
  LocaleID: string;
  Organization: any;
}


export const userDB: Array<UserCSV> =
  [
    {
      UniqueName: 'aagassi',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Alex Agassi',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'adavis',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Arnold Davis',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ghalas',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'akarras',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Arnold Karras',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'bsanders',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'akurosawa',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Atsuko Kurosawa',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'amanning',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Anthony Manning',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'dclark',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'areed',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Alex Reed',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'arooney',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Archie Rooney',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'prozelle',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'arother',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Algar Rother',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'pbrown',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'atippett',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Alex Tippett',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto0',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto0 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto1',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto1 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto2',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto2 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto3',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto3 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto4',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto4 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto5',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto5 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto6',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto6 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto7',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto7 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto8',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto8 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto9',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto9 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'auto10',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Auto10 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bdee',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Barry Dee',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bfu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Biao Fu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bgriese',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Barry Griese',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bjones',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Brian Jones',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'blayne',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Barry Layne',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'bsanders',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bliu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ba Liu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bkilmer',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Brent Kilmet',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bnagurski',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Bailey Nagurski',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'dbutkus',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bsanders',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Bob Sanders',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bsimms',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Bert Simms',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bstarr',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Bob Starr',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'vlombardi',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bwalsh',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Blake Walsh',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cbanks',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Chris Banks',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cevert',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Cheryl Evert',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'clavillette',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Catherine Lavillette',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'bdee',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cmuncie',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Chad Muncie',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'dclark',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cnoll',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Chad Noll',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'arooney',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cspielman',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Carl Spielman',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'hmoore',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'cyxie',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Cyuan You Xie',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dbutkus',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Darryl Butkus',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dclark',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Don Clark',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dfouts',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'David Fouts',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dhampton',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'David Hampton',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dmarino',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'David Marino',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dstephenson',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Don Stephenson',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dtoms',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Don Toms',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mbavaro',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dwalker',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Dennis Walker',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dwang',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Du Wang',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'dwilcox',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Don Wilcox',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'eboozer',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Earl Boozer',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'bsanders',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ehzhang',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'En Hao Zhang',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ekinoshita',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Emi Kinoshita',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'shoshino',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'etunnell',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Earl Tunnell',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'fgifford',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Fred Gifford',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ghalas',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'fharris',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Fred Harris',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'fnan',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Fang Nan',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'fxue',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Fong Xue',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gblanda',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Gene Blanda',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gfencik',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Greg Fencik',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ghalas',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Gene Halas',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'prozelle',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gmcintyre',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Gene McIntyre',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gsayers',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Greg Sayers',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gsun',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Gu Sun',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'dwang',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'habe',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Hiromi Abe',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'hlong',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Herman Long',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'hmatsui',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Haruko Matsui',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'hmoore',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Harvey Moore',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'hqzhu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'He Qin Zhu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'hxgu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Hao Xang Gu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'fnan',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jbgao',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ji Bi Gao',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jbrown',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Joe Brown',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'pbrown',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jgreene',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jim Greene',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jham',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'John Ham',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jinoue',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Junko Inoue',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jjiang',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jhong Jiang',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jkelly',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Joe Kelly',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jlambert',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'John Lambert',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jlofton',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jack Lofton',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'vlombardi',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'GBP',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jmadden',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jared Madden',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'adavis',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jmontana',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jim Montana',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jotto',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Joe Otto',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jrice',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jeremiah Rice',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jthornton',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jack Thornton',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'junitas',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jared Unitas',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jyxu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jin Yu Xu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'tli',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jzorn',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Joe Zorn',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'jgibbs',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Jim Gibbs',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'arooney',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'khouston',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kirk Houston',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jgibbs',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'kaoki',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kikue Aoki',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'khull',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kirk Hull',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'krautenberg',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Karl Rautenberg',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'gmcintyre',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ksato',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kenichiro Sato',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'akurosawa',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'kstabler',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kirk Stabler',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'kstrong',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kirk Strong',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ktanner',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Kirsten Tanner',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'lbarney',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Larry Barney',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'hmoore',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'lcsonka',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Lance Csonka',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ldawson',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Larry Dawson',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'pbrown',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'lgao',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Lan Gao',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'llittle',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Lance Little',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'lswann',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Lester Swann',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ltaylor',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Lance Taylor',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mallen',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mike Allen',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mbavaro',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mike Bavaro',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mditka',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mark Ditka',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'fgifford',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mli',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Meng Li',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'vlombardi',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mmorita',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mutsumi Morita',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'shoshino',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'msingletary',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mark Singletary',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'msugimoto',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Mari Sugimoto',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'nlopez',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Nia Lopez',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ltaylor',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'pbrown',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Phil Brown',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'prozelle',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'phornung',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Phil Hornung',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'vlombardi',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'prozelle',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Paul Rozelle',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: '',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'psampras',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Paul Sampras',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'psimms',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Pete Simms',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'fgifford',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'pwarfield',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Phil Warfield',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rbrown',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ronni Brown',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rcraig',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Robert Craig',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rgrange',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ray Grange',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'dbutkus',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rlott',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Roger Lott',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rmoss',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Raol Moss',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rstaubach',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Robert Staubach',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rtomoda',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ryuko Tomoda',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rwhite',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ron White',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'sconlan',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Sam Conlan',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'sgrogan',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shawn Grogan',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'shoshino',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Setsuko Hoshino',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'shuff',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Steve Huff',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'skobayashi',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shizue Kobayashi',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'slargent',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shawn Largent',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jzorn',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'sowen',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shawn Owen',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'stakida',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shingo Takida',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'rtomoda',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'stasker',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shawn Tasker',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'syoung',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Shawn Young',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'taikman',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tom Aikman',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tbradshaw',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ted Bradshaw',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tdorsett',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tyler Dorsett',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester0',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester0 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester1',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester1 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester2',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester2 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester3',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester3 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester4',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester4 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester5',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester5 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester6',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester6 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester7',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester7 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester8',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester8 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester9',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester9 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tester10',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tester10 User',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'thashimoto',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tetuo Hashimoto',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'pbrown',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'thendricks',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tim Hendricks',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jotto',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tkato',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Takae Kato',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tkurata',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tomohiko Kurata',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tli',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tang Li',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tmifune',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tomoko Mifune',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tsenba',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Tadao Senba',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tthomas',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Ted Thomas',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'twatson',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Toby Watson',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ltaylor',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'twoods',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Thomas Woods',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ltaylor',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'vlombardi',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Victor Lombardi',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'fgifford',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'wperry',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Walter Perry',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'cnoll',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'xhan',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Xhu Han',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'xfdeng',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Xuei Fang Deng',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'yli',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Yan Li',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'bsanders',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'yoshima',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Yoshiko Oshima',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'vlombardi',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'JPY',
      LocaleID: 'ja_JP',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ytittle',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'York Tittle',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'psimms',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ywang',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Yun Wang',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'yye',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Yin Ye',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ywang',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'zwwu',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Zuo Wei Wu',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'pbrown',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'CNY',
      LocaleID: 'zh_CN',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'ehirsch',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Egon Hirsch',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'gallen',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Gene Allen',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'mmeyer',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Markus Meyer',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'bwilson',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Beth Wilson',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'kstabler',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'vlo',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Vincent Lo',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'mditka',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'rberry',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Randy Berry',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'chinton',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Carl Hinton',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'afontaine',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Alain Fontaine',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'adavis',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'fr_FR',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'tzoller',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Thomas Zoller',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'ghalas',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'EUR',
      LocaleID: 'de_DE',
      Organization: 'Buyer'
    },
    {
      UniqueName: 'molson',
      PasswordAdapter: 'PasswordAdapter1',
      Name: 'Max Olson',
      EmailAddress: 'nobody@ansmtp.ariba.com',
      Supervisor: 'jmadden',
      Supervisorpa: 'PasswordAdapter1',
      DefaultCurrency: 'USD',
      LocaleID: 'en_US',
      Organization: 'Buyer'
    }
  ];


